# Generated by Django 5.2.13 on 2026-04-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_user_auto_sync_user_dark_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
