# Generated by Django 6.0.4 on 2026-05-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_event_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignmentsubmission',
            new_name='assignment__assignm_c9693f_idx',
            old_name='assignment__assignm_2d61f5_idx',
        ),
    ]
